workflow

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -49,10 +49,15 @@ jobs:
           HUGO_ENVIRONMENT: production
           HUGO_ENV: production
         run: |
-          hugo --minify --baseURL "https://jtzm.me/"
-      - name: List public directory
+          pwd
+          hugo version
+          hugo --minify --baseURL "https://jtzm.me/" -v
+      - name: Debug Info
         run: |
-          ls -la ./public
+          echo "Current directory contents:"
+          ls -la
+          echo "Public directory contents:"
+          ls -la public || echo "Public directory not found"
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
